Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/bionic64"
#coloquei a minha rede em bridge pra usar o ip que pega do meu roteador
config.vm.network "public_network", bridge:"enp3s0"
    config.vm.provider "virtualbox" do |vb|
# É pedido 2Gb de de ram pra usar kubernetes no nó master
    		vb.memory = "2048"
  	 end
end
